server:
  port: 39001
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.133.171.225:9841/education?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wys&dxf_mysql!
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  global-config:
    db-config:
      logic-delete-field: isDeleted
  cloud:
    nacos:
      discovery:
        #注册nacos
        server-addr: 101.133.171.225:9703
  application:
    name: service-cms
  #redis
  redis:
    host: 101.133.171.225
    port: 9702
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: wys&dxf_mysql!
#SQL打印
logging:
  level:
    cool.delete.cms.mapper: debug
#扫描xml
mybatis-plus:
  mapper-locations: classpath:cool/delete/cms/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

