aliyun:
    AccessKey:
      AccessKeyID: LTAI4GDFMvtdUaz83mqxwmPY
      AccessKeySecret: ScsX7jkzXB2onZOkcwYnCbLq7PSbPm
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      file:
        bucketName: file-online
server:
  port: 39004
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: 101.133.171.225:9703
