server:
  port: 8005
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        #注册nacos
        server-addr: 127.0.0.1:8848
  application:
    name: service-cms
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
#SQL打印
logging:
  level:
    cool.delete.edu.mapper: debug

qiniu:
  AccessKey:
    AccessKeyID: iqJunHaPjJh4WACJrn1Z6mB7b9S6dhTyYXa8Ar-_
    AccessKeySecret: KVV99I-HdLB90IEO_NEw4T4ougLjDwiGyK9RRARf
  TemplateId: 1256121695144521728