server:
  port: 39005
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        #注册nacos
        server-addr: 101.133.171.225:9703
  application:
    name: service-sms
  #redis
  redis:
    host: 101.133.171.225
    port: 9702
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: wys&dxf_mysql!
#SQL打印
logging:
  level:
    cool.delete.edu.mapper: debug

qiniu:
  AccessKey:
    AccessKeyID: iqJunHaPjJh4WACJrn1Z6mB7b9S6dhTyYXa8Ar-_
    AccessKeySecret: KVV99I-HdLB90IEO_NEw4T4ougLjDwiGyK9RRARf
  TemplateId: 1256121695144521728